name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  pr-validation:
    name: PR Title & Description Check
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false

      - name: Check PR description
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            if (!prBody || prBody.length < 20) {
              core.setFailed('PR description is too short. Please provide a detailed description.');
            }

  size-label:
    name: Add Size Label
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add size label
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: 10
          s_label: 'size/s'
          s_max_size: 100
          m_label: 'size/m'
          m_max_size: 500
          l_label: 'size/l'
          l_max_size: 1000
          xl_label: 'size/xl'
          fail_if_xl: false

  comment-pr:
    name: Comment on PR
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    
    steps:
      - name: Add welcome comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Thanks for opening this PR!
              
              **Automated checks will run shortly:**
              - ✅ Code quality (ESLint, Prettier)
              - ✅ Tests (Jest with coverage)
              - ✅ Build verification
              - ✅ Security scanning
              
              Please ensure all checks pass before requesting review.`
            })

  label-by-files:
    name: Auto-label by Changed Files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Label based on changed files
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
